// eslint-disable-next-line import/prefer-default-export
export const AUTH_TYPES = {
  // Local State Actions
  SET_LOGIN_FIELD: 'SET_LOGIN_FIELD',
  SET_REGISTER_FIELD: 'SET_REGISTER_FIELD',
  TOGGLE_POPUP: 'TOGGLE_POPUP',
  TOGGLE_REGISTER_FORM: 'TOGGLE_REGISTER_FORM',
  SET_USER_NAME: 'SET_USER_NAME',
  SET_SCHOOL_NAME: 'SET_SCHOOL_NAME',
  // API Related Actions
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
};
