// eslint-disable-next-line import/prefer-default-export
export const TEACHER_TYPES = {
  // API Related Actions
  ADD_NEW_TEACHER: 'ADD_NEW_TEACHER',
  UPDATE_EXISTING_TEACHER: 'UPDATE_EXISTING_TEACHER',
  REMOVE_EXISTING_TEACHER: 'REMOVE_EXISTING_TEACHER',
  SET_ALL_TEACHERS: 'SET_ALL_TEACHERS',
  SET_TEACHERS_FOR_TABLE: 'SET_TEACHERS_FOR_TABLE',
  // Local State Changes
  TOGGLE_TEACHER_POPUP: 'TOGGLE_TEACHER_POPUP',
  SET_FIELD_DATA_FOR_TEACHER: 'SET_FIELD_DATA_FOR_TEACHER',
  TOGGLE_TEACHER_MODAL: 'TOGGLE_TEACHER_MODAL',
  // Reset to Initial State
  CLEAR_STATE: 'CLEAR_STATE',
};
