// eslint-disable-next-line import/prefer-default-export
export const TEACHER_TYPES = {
  SET_FIELD_DATA: 'SET_FIELD_DATA',
  SET_ALL_TEACHERS: 'SET_ALL_TEACHERS',
  TOGGLE_TEACHER_MODAL: 'TOGGLE_TEACHER_MODAL',
  ADD_NEW_TEACHER: 'ADD_NEW_TEACHER',
  UPDATE_EXISTING_TEACHER: 'UPDATE_EXISTING_TEACHER',
  REMOVE_EXISTING_TEACHER: 'REMOVE_EXISTING_TEACHER',
  TOGGLE_POPUP: 'TOGGLE_POPUP',
};
