// eslint-disable-next-line import/prefer-default-export
export const TIMETABLE_TYPES = {
  // API Related Actions
  SET_SCHOOL_TIMETABLE: 'SET_SCHOOL_TIMETABLE',
  SET_TIMETABLE: 'SET_TIMETABLE',
  SET_SUGGESTIONS: 'SET_SUGGESTIONS',
  // Local State Updating
  SET_NUM_PERIODS: 'SET_NUM_PERIODS',
  SET_ENTITY_TYPE: 'SET_ENTITY_TYPE',
  SET_ENTITY_ID: 'SET_ENTITY_ID',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  TOGGLE_TIMETABLE_POPUP: 'TOGGLE_TIMETABLE_POPUP',
  POPULATE_ENTITY_IDS: 'POPULATE_ENTITY_IDS',
  TOGGLE_EDIT_TIMETABLE_MODAL: 'TOGGLE_EDIT_TIMETABLE_MODAL',
  RESET_SUGGESTIONS: 'RESET_SUGGESTIONS',
  // Reset to Initial State
  CLEAR_STATE: 'CLEAR_STATE',
};
