// Errors
export const GET_ERRORS = 'GET_ERRORS';
export const SET_RANDOM_ERRORS = 'SET_RANDOM_ERRORS';

// Users
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

// Teachers
export const SET_ALL_TEACHERS = 'SET_ALL_TEACHERS';
export const ADD_NEW_TEACHER = 'ADD_NEW_TEACHER';
export const UPDATE_EXISTING_TEACHER = 'UPDATE_EXISTING_TEACHER';

// Classes
export const ADD_NEW_CLASSES = 'ADD_NEW_CLASSES';
export const SET_ALL_CLASSES = 'SET_ALL_CLASSES';
