export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
export const SET_ALL_TEACHERS = 'SET_ALL_TEACHERS';
export const ADD_NEW_TEACHER = 'ADD_NEW_TEACHER';
